addSbtPlugin("pl.project13.scala" % "sbt-jmh"          % "0.4.8")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"     % "2.6.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"      % "1.22.0")
addSbtPlugin("org.scala-native"   % "sbt-scala-native" % "0.5.12")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"   % "1.11.2")
